# =============================================================================
# LUMEN v2 — Network Meta-Analysis R Template
# =============================================================================
# Auto-generated by src/utils/nma.py. Do NOT edit manually.
# Engine: netmeta (frequentist NMA, graph-theoretic approach)
# No JAGS/Stan dependency required.
# =============================================================================

suppressPackageStartupMessages({
  library(netmeta)
  library(meta)
  library(metafor)
  library(jsonlite)
})

# --- 0. Configuration (injected by Python) ---
OUTPUT_DIR   <- "{{output_dir}}"
FIG_DIR      <- file.path(OUTPUT_DIR, "figures")
TBL_DIR      <- file.path(OUTPUT_DIR, "tables")
RESULTS_JSON <- file.path(OUTPUT_DIR, "nma_results.json")

EFFECT_MEASURE  <- "{{effect_measure}}"
METHOD_TAU      <- "{{method_tau}}"
REFERENCE_GROUP <- {{reference_group}}
SMALL_VALUES    <- "{{small_values}}"

RUN_CONSISTENCY    <- {{run_consistency}}
RUN_NODE_SPLITTING <- {{run_node_splitting}}
RUN_NET_HEAT       <- {{run_net_heat}}
RUN_LOO            <- {{run_loo}}
RUN_NETWORK_GRAPH  <- {{run_network_graph}}
RUN_FOREST         <- {{run_forest}}
RUN_LEAGUE         <- {{run_league}}
RUN_LEAGUE_HEATMAP <- {{run_league_heatmap}}
RUN_FUNNEL         <- {{run_funnel}}
RUN_RANKING        <- {{run_ranking}}

FIG_WIDTH  <- 10
FIG_HEIGHT <- 8
FIG_DPI    <- 300

dir.create(FIG_DIR, recursive = TRUE, showWarnings = FALSE)
dir.create(TBL_DIR, recursive = TRUE, showWarnings = FALSE)

results <- list()

# --- 1. Load data (injected as CSV string) ---
data_csv <- "{{data_csv}}"
nma_data <- read.csv(textConnection(data_csv), stringsAsFactors = FALSE)

cat("Studies loaded:", nrow(nma_data), "\n")
cat("Columns:", paste(names(nma_data), collapse = ", "), "\n")
cat("Unique studies:", length(unique(nma_data$studlab)), "\n")
cat("Treatments:", paste(sort(unique(c(nma_data$treat1, nma_data$treat2))), collapse = ", "), "\n")

results$n_studies    <- length(unique(nma_data$studlab))
results$n_contrasts  <- nrow(nma_data)
results$treatments   <- sort(unique(c(nma_data$treat1, nma_data$treat2)))
results$n_treatments <- length(results$treatments)

# --- 2. Check network connectivity ---
nc <- netconnection(nma_data$treat1, nma_data$treat2, nma_data$studlab)
results$n_subnets <- nc$n.subnets
results$connected <- (nc$n.subnets == 1)

if (nc$n.subnets > 1) {
  cat("WARNING: Disconnected network with", nc$n.subnets, "sub-networks.\n")
  results$error <- "Disconnected network — NMA requires a single connected component."
  write(toJSON(results, auto_unbox = TRUE, pretty = TRUE), RESULTS_JSON)
  quit(status = 1)
}
cat("Network is fully connected.\n")

# --- 3. Fit NMA model ---
cat("\n=== Fitting NMA (netmeta, REML) ===\n")

if (is.null(REFERENCE_GROUP) || REFERENCE_GROUP == "" || REFERENCE_GROUP == "NULL") {
  REFERENCE_GROUP <- NULL
}

net <- netmeta(
  TE      = nma_data$TE,
  seTE    = nma_data$seTE,
  treat1  = nma_data$treat1,
  treat2  = nma_data$treat2,
  studlab = nma_data$studlab,
  sm         = EFFECT_MEASURE,
  random     = TRUE,
  common     = TRUE,
  method.tau = METHOD_TAU,
  reference.group = REFERENCE_GROUP,
  tol.multiarm = 1.0,
  details.chkmultiarm = TRUE
)

cat("Model fitted successfully.\n")
cat("tau^2 =", net$tau2, "\n")
cat("I^2 =", round(net$I2 * 100, 1), "%\n")

# Store core results
results$tau2  <- net$tau2
results$I2    <- round(net$I2 * 100, 1)
results$Q     <- net$Q
results$df_Q  <- net$df.Q
results$pval_Q <- net$pval.Q
results$effect_measure <- EFFECT_MEASURE
results$method_tau     <- METHOD_TAU
results$reference_group <- if (is.null(net$reference.group)) results$treatments[1] else net$reference.group

# Extract pairwise estimates (random-effects)
ref <- results$reference_group
treats <- results$treatments[results$treatments != ref]
pairwise_results <- list()
for (t in treats) {
  idx_t   <- which(net$trts == t)
  idx_ref <- which(net$trts == ref)
  te    <- net$TE.random[idx_t, idx_ref]
  lower <- net$lower.random[idx_t, idx_ref]
  upper <- net$upper.random[idx_t, idx_ref]
  pval  <- net$pval.random[idx_t, idx_ref]

  is_ratio <- EFFECT_MEASURE %in% c("RR", "OR", "HR")
  pairwise_results[[t]] <- list(
    treatment = t,
    TE        = round(te, 4),
    lower     = round(lower, 4),
    upper     = round(upper, 4),
    pval      = round(pval, 6),
    TE_exp    = if (is_ratio) round(exp(te), 4) else NULL,
    lower_exp = if (is_ratio) round(exp(lower), 4) else NULL,
    upper_exp = if (is_ratio) round(exp(upper), 4) else NULL
  )
}
results$pairwise_vs_reference <- pairwise_results

# --- 4. Treatment ranking (P-score) ---
if (RUN_RANKING) {
  cat("\n=== Treatment Ranking (P-score) ===\n")
  ranking <- netrank(net, small.values = SMALL_VALUES)
  # netmeta >= 7.0 uses ranking.random; older uses Pscore.random
  pscore <- if (!is.null(ranking$ranking.random)) ranking$ranking.random
            else if (!is.null(ranking$Pscore.random)) ranking$Pscore.random
            else ranking$Pscore
  rank_df <- data.frame(
    treatment = names(pscore),
    p_score   = round(as.numeric(pscore), 4),
    stringsAsFactors = FALSE
  )
  rank_df <- rank_df[order(-rank_df$p_score), ]
  rank_df$rank <- seq_len(nrow(rank_df))
  results$rankings <- rank_df
  cat("Rankings:\n")
  print(rank_df)

  write.csv(rank_df, file.path(TBL_DIR, "nma_rankings.csv"), row.names = FALSE)

  # P-score bar chart
  png(file.path(FIG_DIR, "nma_ranking_pscore.png"),
      width = FIG_WIDTH, height = max(4, nrow(rank_df) * 0.6),
      units = "in", res = FIG_DPI)
  par(mar = c(4, 10, 3, 2))
  barplot(
    rev(rank_df$p_score),
    names.arg = rev(rank_df$treatment),
    horiz = TRUE, las = 1,
    col = "steelblue", border = NA,
    xlim = c(0, 1),
    xlab = "P-score",
    main = "Treatment Ranking (P-score)"
  )
  dev.off()
  cat("Ranking plot saved.\n")
}

# --- 5. Network graph ---
if (RUN_NETWORK_GRAPH) {
  cat("\n=== Network Graph ===\n")
  png(file.path(FIG_DIR, "nma_network_graph.png"),
      width = FIG_WIDTH, height = FIG_HEIGHT, units = "in", res = FIG_DPI)
  tryCatch({
    # Node size proportional to number of studies involving each treatment
    n_per_treat <- tapply(
      c(nma_data$studlab, nma_data$studlab),
      c(nma_data$treat1, nma_data$treat2),
      function(x) length(unique(x))
    )
    node_sizes <- sqrt(as.numeric(n_per_treat[net$trts])) * 1.8 + 2

    # Use circular layout for cleaner small networks
    n_trts <- length(net$trts)
    layout_seq <- if (n_trts <= 5) "circle" else "optimal"

    netgraph(
      net,
      seq = layout_seq,
      number.of.studies = TRUE,
      cex.points = node_sizes,
      col.points = "#4682B4",
      col = "#666666",
      plastic = FALSE,
      thickness = "number.of.studies",
      points = TRUE,
      cex.number = 1.5,
      offset = 0.035,
      adj = 0.5,
      lwd = 2
    )
    # Add heterogeneity annotation
    i2_val <- if (!is.null(net$I2) && !is.na(net$I2)) round(net$I2 * 100, 1) else "NA"
    tau2_val <- if (!is.null(net$tau2)) round(net$tau2, 3) else "NA"
    k_val <- length(unique(nma_data$studlab))
    mtext(paste0("k = ", k_val, ";  I\u00B2 = ", i2_val, "%;  \u03C4\u00B2 = ", tau2_val),
          side = 1, line = 0, cex = 1.0, col = "grey30")
  }, error = function(e) {
    cat("Network graph error (non-fatal):", conditionMessage(e), "\n")
    plot.new()
    text(0.5, 0.5, paste("Network graph error:", conditionMessage(e)), cex = 0.8)
  })
  dev.off()
  cat("Network graph saved.\n")
}

# --- 6. Forest plot ---
if (RUN_FOREST) {
  cat("\n=== Forest Plot ===\n")
  ref_t <- results$reference_group
  tryCatch({
    n_trts <- length(net$trts) - 1  # minus reference
    png(file.path(FIG_DIR, "nma_forest.png"),
        width = 12, height = max(4, n_trts * 1.5 + 2),
        units = "in", res = FIG_DPI)
    forest(net,
           reference.group = ref_t,
           sortvar = TE,
           smlab = paste0("Treatments vs ", ref_t,
                          "\n(I\u00B2=", round(net$I2 * 100, 1), "%, ",
                          "\u03C4\u00B2=", round(net$tau2, 3), ", ",
                          "k=", results$n_studies, ")"),
           drop.reference.group = TRUE,
           label.left  = paste("Favours", ref_t),
           label.right = "Favours treatment",
           xlim = NULL)
    dev.off()
    cat("Forest plot saved.\n")
  }, error = function(e) {
    try(dev.off(), silent = TRUE)
    cat("Forest plot error (non-fatal):", conditionMessage(e), "\n")
  })
}

# --- 7. League table ---
if (RUN_LEAGUE) {
  cat("\n=== League Table ===\n")
  tryCatch({
  if (RUN_RANKING) {
    league <- netleague(net, random = TRUE, seq = ranking, digits = 2)
  } else {
    league <- netleague(net, random = TRUE, digits = 2)
  }
  league_df <- as.data.frame(league$random)
  write.csv(league_df, file.path(TBL_DIR, "nma_league_table.csv"))
  results$league_table <- league_df
  cat("League table saved.\n")
  }, error = function(e) {
    cat("League table error (non-fatal):", conditionMessage(e), "\n")
  })
}

# --- 8. League table heatmap ---
if (RUN_LEAGUE_HEATMAP && RUN_LEAGUE) {
  tryCatch({
  cat("\n=== League Table Heatmap ===\n")

  is_ratio <- EFFECT_MEASURE %in% c("RR", "OR", "HR")
  league_matrix <- league$random
  treat_order <- if (RUN_RANKING) rank_df$treatment else sort(net$trts)
  n_treats <- length(treat_order)

  heatmap_rows <- list()
  for (i in seq_len(nrow(league_matrix))) {
    for (j in seq_len(ncol(league_matrix))) {
      if (i == j) next
      cell_text <- as.character(league_matrix[i, j])
      if (is.na(cell_text) || cell_text == "") next

      m <- regmatches(cell_text, regexec(
        "([0-9.-]+)\\s*[\\[\\(]([0-9.-]+)[,;]\\s*([0-9.-]+)[\\]\\)]", cell_text
      ))[[1]]

      if (length(m) == 4) {
        est <- as.numeric(m[2])
        lo  <- as.numeric(m[3])
        hi  <- as.numeric(m[4])
        null_val <- if (is_ratio) 1 else 0
        sig <- (lo > null_val) || (hi < null_val)
        fill_val <- if (is_ratio) log(est) else est

        heatmap_rows[[length(heatmap_rows) + 1]] <- data.frame(
          row_treat = rownames(league_matrix)[i],
          col_treat = colnames(league_matrix)[j],
          estimate  = est, lower = lo, upper = hi,
          sig = sig, fill_val = fill_val,
          label = trimws(cell_text),
          stringsAsFactors = FALSE
        )
      }
    }
  }

  if (length(heatmap_rows) > 0) {
    hm_df <- do.call(rbind, heatmap_rows)
    hm_df$row_treat <- factor(hm_df$row_treat, levels = treat_order)
    hm_df$col_treat <- factor(hm_df$col_treat, levels = treat_order)
    fill_limit <- max(abs(hm_df$fill_val), na.rm = TRUE)

    fig_size <- max(6, n_treats * 1.4)
    png(file.path(FIG_DIR, "nma_league_heatmap.png"),
        width = fig_size, height = fig_size * 0.85, units = "in", res = FIG_DPI)

    par(mar = c(6, 6, 3, 2))
    # Use base R heatmap since ggplot2 may not be available
    mat <- matrix(NA, nrow = n_treats, ncol = n_treats,
                  dimnames = list(treat_order, treat_order))
    for (r in seq_len(nrow(hm_df))) {
      mat[as.character(hm_df$row_treat[r]), as.character(hm_df$col_treat[r])] <- hm_df$fill_val[r]
    }
    # Color palette: blue (favours row) -> white (null) -> red (favours col)
    n_colors <- 100
    cols <- colorRampPalette(c("#2166AC", "white", "#B2182B"))(n_colors)
    breaks <- seq(-fill_limit, fill_limit, length.out = n_colors + 1)
    image(1:n_treats, 1:n_treats, t(mat[n_treats:1, ]),
          col = cols, breaks = breaks,
          axes = FALSE, xlab = "", ylab = "")
    axis(1, at = 1:n_treats, labels = treat_order, las = 2, cex.axis = 0.8)
    axis(2, at = 1:n_treats, labels = rev(treat_order), las = 1, cex.axis = 0.8)
    title("League Table Heatmap")
    # Add text labels
    for (r in seq_len(nrow(hm_df))) {
      xi <- which(treat_order == as.character(hm_df$col_treat[r]))
      yi <- n_treats + 1 - which(treat_order == as.character(hm_df$row_treat[r]))
      font_face <- if (hm_df$sig[r]) 2 else 1
      cex_val <- if (n_treats <= 5) 0.6 else if (n_treats <= 8) 0.5 else 0.4
      text(xi, yi, hm_df$label[r], cex = cex_val, font = font_face)
    }
    dev.off()
    cat("League heatmap saved.\n")
  }
  }, error = function(e) {
    try(dev.off(), silent = TRUE)
    cat("League heatmap error (non-fatal):", conditionMessage(e), "\n")
  })
}

# --- 9. Comparison-adjusted funnel plot ---
if (RUN_FUNNEL) {
  cat("\n=== Funnel Plot ===\n")
  png(file.path(FIG_DIR, "nma_funnel.png"),
      width = FIG_WIDTH, height = FIG_HEIGHT, units = "in", res = FIG_DPI)
  tryCatch({
    if (RUN_RANKING) {
      # order must be a permutation of 1:n_treats (rank order by P-score)
      ord <- rank(-pscore)
      funnel(net, order = ord, pch = 16, col = "steelblue", legend = TRUE)
    } else {
      funnel(net, pch = 16, col = "steelblue", legend = TRUE)
    }
  }, error = function(e) {
    cat("Funnel plot error (non-fatal):", conditionMessage(e), "\n")
    tryCatch(funnel(net, pch = 16, col = "steelblue"),
             error = function(e2) {
               plot.new()
               text(0.5, 0.5, paste("Funnel plot unavailable:", conditionMessage(e2)), cex=0.8)
             })
  })
  dev.off()
  cat("Funnel plot saved.\n")
}

# --- 10. Consistency assessment ---
if (RUN_CONSISTENCY) {
  cat("\n=== Consistency Assessment (Design Decomposition) ===\n")
  dd <- tryCatch(decomp.design(net), error = function(e) {
    cat("Design decomposition failed:", e$message, "\n")
    NULL
  })
  if (!is.null(dd)) {
    results$consistency <- list(
      Q_total            = dd$Q.decomp$Q[1],
      Q_between_designs  = dd$Q.decomp$Q[2],
      Q_within_designs   = dd$Q.decomp$Q[3],
      pval_total         = dd$Q.decomp$pval[1],
      pval_between       = dd$Q.decomp$pval[2],
      pval_within        = dd$Q.decomp$pval[3],
      inconsistency_detected = (dd$Q.decomp$pval[2] < 0.05)
    )
    cat("Q_between p-value:", dd$Q.decomp$pval[2], "\n")
  }
}

# --- 11. Node-splitting ---
if (RUN_NODE_SPLITTING) {
  cat("\n=== Node-Splitting ===\n")
  ns <- tryCatch(netsplit(net), error = function(e) {
    cat("Node-splitting failed:", e$message, "\n")
    NULL
  })
  if (!is.null(ns)) {
    # Extract node-splitting results — netmeta >= 7 changed output structure
    ns_df <- tryCatch(as.data.frame(ns), error = function(e) {
      tryCatch({
        data.frame(
          comparison = ns$comparison,
          direct = ns$direct.random$TE,
          indirect = ns$indirect.random$TE,
          diff = ns$compare.random$TE,
          p = ns$compare.random$p,
          stringsAsFactors = FALSE
        )
      }, error = function(e2) NULL)
    })

    if (!is.null(ns_df)) {
      results$node_splitting <- ns_df
      write.csv(ns_df, file.path(TBL_DIR, "nma_node_splitting.csv"), row.names = FALSE)
    }

    tryCatch({
      png(file.path(FIG_DIR, "nma_netsplit_forest.png"),
          width = 12, height = max(8, length(ns$comparison) * 1.5),
          units = "in", res = FIG_DPI)
      forest(ns)
      dev.off()
      cat("Node-splitting forest saved.\n")
    }, error = function(e) {
      try(dev.off(), silent = TRUE)
      cat("Node-splitting forest error (non-fatal):", conditionMessage(e), "\n")
    })
  }
}

# --- 12. Net heat plot (skip for small networks — uninformative) ---
if (RUN_NET_HEAT && length(net$trts) >= 5) {
  cat("\n=== Net Heat Plot ===\n")
  tryCatch({
    png(file.path(FIG_DIR, "nma_netheat.png"),
        width = FIG_WIDTH, height = FIG_HEIGHT, units = "in", res = FIG_DPI)
    netheat(net, random = TRUE)
    dev.off()
    cat("Net heat plot saved.\n")
  }, error = function(e) {
    try(dev.off(), silent = TRUE)
    cat("Net heat plot failed:", e$message, "\n")
  })
} else if (RUN_NET_HEAT) {
  cat("Skipping net heat plot (< 5 treatments, uninformative).\n")
}

# --- 13. Leave-one-out sensitivity ---
if (RUN_LOO) {
  cat("\n=== Leave-One-Out Analysis ===\n")
  studies <- unique(nma_data$studlab)
  loo_results <- list()

  for (s in studies) {
    data_loo <- nma_data[nma_data$studlab != s, ]

    nc_loo <- tryCatch(
      netconnection(data_loo$treat1, data_loo$treat2, data_loo$studlab),
      error = function(e) NULL
    )

    if (is.null(nc_loo) || nc_loo$n.subnets > 1) {
      cat("Skipping", s, "- removal disconnects network\n")
      next
    }

    net_loo <- tryCatch(
      netmeta(data_loo$TE, data_loo$seTE, data_loo$treat1, data_loo$treat2,
              data_loo$studlab, sm = EFFECT_MEASURE, random = TRUE,
              method.tau = METHOD_TAU),
      error = function(e) NULL
    )

    if (!is.null(net_loo)) {
      loo_results[[s]] <- list(
        excluded = s,
        tau2     = round(net_loo$tau2, 4),
        I2       = round(net_loo$I2 * 100, 1)
      )
    }
  }

  if (length(loo_results) > 0) {
    loo_df <- do.call(rbind, lapply(loo_results, function(x) {
      data.frame(excluded = x$excluded, tau2 = x$tau2, I2_pct = x$I2,
                 stringsAsFactors = FALSE)
    }))
    results$leave_one_out <- loo_df
    write.csv(loo_df, file.path(TBL_DIR, "nma_leave_one_out.csv"), row.names = FALSE)
    cat("LOO results saved.\n")
  }
}

# --- 14. CINeMA template ---
cat("\n=== CINeMA Template ===\n")
cinema_treatments <- sort(unique(c(nma_data$treat1, nma_data$treat2)))
cinema_template <- expand.grid(
  treat1 = cinema_treatments,
  treat2 = cinema_treatments,
  stringsAsFactors = FALSE
)
cinema_template <- cinema_template[cinema_template$treat1 < cinema_template$treat2, ]
cinema_template$within_study_bias  <- NA
cinema_template$across_study_bias  <- NA
cinema_template$indirectness       <- NA
cinema_template$imprecision        <- NA
cinema_template$heterogeneity      <- NA
cinema_template$incoherence        <- NA
cinema_template$overall_certainty  <- NA

write.csv(cinema_template, file.path(TBL_DIR, "cinema_template.csv"), row.names = FALSE)
results$cinema_comparisons <- nrow(cinema_template)
cat("CINeMA template generated:", nrow(cinema_template), "comparisons.\n")

# --- 15. Write results JSON ---
cat("\n=== Saving Results ===\n")
write(toJSON(results, auto_unbox = TRUE, pretty = TRUE, force = TRUE), RESULTS_JSON)
cat("Results saved to", RESULTS_JSON, "\n")
cat("NMA analysis complete.\n")
